twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/templates': client
        '%kernel.project_dir%/public/img': img
        '%kernel.project_dir%/public/css': css
        '%kernel.project_dir%/public/js': js
    form_themes: ['bootstrap_5_layout.html.twig']
when@test:
    twig:
        strict_variables: true
